[files]
current_page=-1
recent_files=/home/jay/Builds/game/assets/game.py;/home/jay/Builds/game/game.py;/home/jay/Downloads/default.nix;/home/jay/AB_Scripts/fzfm.sh;/run/media/jay/EEA9-ADFA/configfiles/wezterm/wezterm.lua;/home/jay/.config/qutebrowser/quickmarks;/home/jay/.config/qutebrowser/config.py;/home/jay/.config/qutebrowser/autoconfig.yml;/home/jay/.config/fish/functions/fish_prompt.fish;/home/jay/.config/fish/functions/fish_right_prompt.fish;
recent_projects=

[VTE]
last_dir=/home/jay

[project]
session_file=
project_file_path=/home/jay/projects

[geany]
treeview_position=230
msgwindow_position=1022
geometry=24;21;936;1088;0;
sidebar_page=2

[search]
find_all_expanded=true
replace_all_expanded=false
position_find_x=26
position_find_y=23
position_replace_x=26
position_replace_y=23
position_fif_x=26
position_fif_y=23

[plugins]
load_plugins=true
custom_plugin_path=
active_plugins=/usr/lib/geany/addons.so;/usr/lib/geany/autoclose.so;/usr/lib/geany/automark.so;/usr/lib/geany/geanygendoc.so;/usr/lib/geany/filebrowser.so;/usr/lib/geany/git-changebar.so;/usr/lib/geany/lsp.so;/usr/lib/geany/geanylua.so;/usr/lib/geany/spellcheck.so;/usr/lib/geany/splitwindow.so;/usr/lib/geany/treebrowser.so;/usr/lib/geany/updatechecker.so;/usr/lib/geany/vimode.so;/usr/lib/geany/xmlsnippets.so;
